[package]
name = "marvfirst_main"
version = "0.1.0"
authors = ["Marvin Mednick <mmednick@gmail.com>"]
edition = "2021"

[build]
target = "wasm32-unknown-unknown"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "4.0.0-pre.2"
serde = { version = "1.0", features = ['derive'] }

